#############################################################################
# Makefile for building: qiscp
# Generated by qmake (2.01a) (Qt 4.8.6) on: ma syyskuuta 8 16:34:49 2014
# Project:  qiscp.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile qiscp.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libqiscp \
		sub-clitest \
		sub-qmltest

libqiscp//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libqiscp/ || $(MKDIR) libqiscp/ 
	cd libqiscp/ && $(QMAKE) /home/milang/qt/qiscp/libqiscp/libqiscp.pro -o $(MAKEFILE)
sub-libqiscp-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libqiscp/ || $(MKDIR) libqiscp/ 
	cd libqiscp/ && $(QMAKE) /home/milang/qt/qiscp/libqiscp/libqiscp.pro -o $(MAKEFILE)
sub-libqiscp: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE)
sub-libqiscp-make_default: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) 
sub-libqiscp-make_first: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) first
sub-libqiscp-all: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) all
sub-libqiscp-clean: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) clean
sub-libqiscp-distclean: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libqiscp-install_subtargets: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) install
sub-libqiscp-uninstall_subtargets: libqiscp//$(MAKEFILE) FORCE
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) uninstall
clitest//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) clitest/ || $(MKDIR) clitest/ 
	cd clitest/ && $(QMAKE) /home/milang/qt/qiscp/clitest/clitest.pro -o $(MAKEFILE)
sub-clitest-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) clitest/ || $(MKDIR) clitest/ 
	cd clitest/ && $(QMAKE) /home/milang/qt/qiscp/clitest/clitest.pro -o $(MAKEFILE)
sub-clitest: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE)
sub-clitest-make_default: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) 
sub-clitest-make_first: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) first
sub-clitest-all: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) all
sub-clitest-clean: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) clean
sub-clitest-distclean: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) distclean
sub-clitest-install_subtargets: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) install
sub-clitest-uninstall_subtargets: clitest//$(MAKEFILE) FORCE
	cd clitest/ && $(MAKE) -f $(MAKEFILE) uninstall
qmltest//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qmltest/ || $(MKDIR) qmltest/ 
	cd qmltest/ && $(QMAKE) /home/milang/qt/qiscp/qmltest/qmltest.pro -o $(MAKEFILE)
sub-qmltest-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qmltest/ || $(MKDIR) qmltest/ 
	cd qmltest/ && $(QMAKE) /home/milang/qt/qiscp/qmltest/qmltest.pro -o $(MAKEFILE)
sub-qmltest: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE)
sub-qmltest-make_default: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) 
sub-qmltest-make_first: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) first
sub-qmltest-all: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) all
sub-qmltest-clean: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) clean
sub-qmltest-distclean: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qmltest-install_subtargets: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) install
sub-qmltest-uninstall_subtargets: qmltest//$(MAKEFILE) FORCE
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qiscp.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile qiscp.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qiscp.pro

qmake_all: sub-libqiscp-qmake_all sub-clitest-qmake_all sub-qmltest-qmake_all FORCE

make_default: sub-libqiscp-make_default sub-clitest-make_default sub-qmltest-make_default FORCE
make_first: sub-libqiscp-make_first sub-clitest-make_first sub-qmltest-make_first FORCE
all: sub-libqiscp-all sub-clitest-all sub-qmltest-all FORCE
clean: sub-libqiscp-clean sub-clitest-clean sub-qmltest-clean FORCE
distclean: sub-libqiscp-distclean sub-clitest-distclean sub-qmltest-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libqiscp-install_subtargets sub-clitest-install_subtargets sub-qmltest-install_subtargets FORCE
uninstall_subtargets: sub-libqiscp-uninstall_subtargets sub-clitest-uninstall_subtargets sub-qmltest-uninstall_subtargets FORCE

sub-libqiscp-check: libqiscp/$(MAKEFILE)
	cd libqiscp/ && $(MAKE) -f $(MAKEFILE) check
sub-clitest-check: clitest/$(MAKEFILE)
	cd clitest/ && $(MAKE) -f $(MAKEFILE) check
sub-qmltest-check: qmltest/$(MAKEFILE)
	cd qmltest/ && $(MAKE) -f $(MAKEFILE) check
check: sub-libqiscp-check sub-clitest-check sub-qmltest-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

